### ISSUE TITLE
Multiple workers ability

### ISSUE THREAD

**Issue by tyctor** [gavinwahl/django-postgres-queue#15]
Hi 

i like this module, and i want to migrate my application to use it.

my current setup is that i am using `supervisord` to run workers for different tasks
and each such worker has parameter `--number-of-threads`, `--number-of-processes`
this parameter tells how many threads/processes each worker will run in parallel

is there ability in this module to run multiple workers at parallel?
probably i need to create some kind of `WorkerPool` class and run `call_command('worker')`
inside it in multiple processes or is there some natural way in this module how to run multiple workers?

thanks for any answer

**Comment by gavinwahl** [comment]
I simply run multiple processes of the regular worker. Does supervisord have the ability to start the same process multiple times? I don't use supervisord, and instead use a bash script to start the workers:

```
for i in `seq $DPQ_WORKER_COUNT`
do
 python manage.py worker &
done
```

**Comment by tyctor** [comment]
thanks, will do it same way, `supervisord` is able to start process multiple times
